-- Korean Glossary (한국어 전문 용어 강제 정렬 Seed)
-- For backward compatibility with upstream defaults, optional.

INSERT OR REPLACE INTO dictionary (id, workspace_id, key, value) VALUES 
('ko-1', 'default', '인증', 'authentication'),
('ko-2', 'default', '설정', 'configuration'),
('ko-3', 'default', '배포', 'deployment'),
('ko-4', 'default', '설치', 'installation'),
('ko-5', 'default', '데이터베이스', 'database'),
('ko-6', 'default', '서버', 'server'),
('ko-7', 'default', '클라이언트', 'client'),
('ko-8', 'default', '사용자', 'user'),
('ko-9', 'default', '관리자', 'admin'),
('ko-10', 'default', '보안', 'security'),
('ko-11', 'default', '권한', 'permission'),
('ko-12', 'default', '로그인', 'login'),
('ko-13', 'default', '비밀번호', 'password'),
('ko-14', 'default', '검색', 'search'),
('ko-15', 'default', '문서', 'document'),
('ko-16', 'default', '파일', 'file'),
('ko-17', 'default', '업로드', 'upload'),
('ko-18', 'default', '다운로드', 'download'),
('ko-19', 'default', '에러', 'error'),
('ko-20', 'default', '버그', 'bug'),
('ko-21', 'default', '수정', 'fix'),
('ko-22', 'default', '테스트', 'test'),
('ko-23', 'default', '빌드', 'build'),
('ko-24', 'default', '실행', 'run'),
('ko-25', 'default', '함수', 'function'),
('ko-26', 'default', '변수', 'variable'),
('ko-27', 'default', '타입', 'type'),
('ko-28', 'default', '모듈', 'module'),
('ko-29', 'default', '패키지', 'package'),
('ko-30', 'default', '라이브러리', 'library'),
('ko-31', 'default', '프레임워크', 'framework'),
('ko-32', 'default', '컴포넌트', 'component'),
('ko-33', 'default', '인터페이스', 'interface'),
('ko-34', 'default', '환경변수', 'environment variable'),
('ko-35', 'default', '캐시', 'cache'),
('ko-36', 'default', '큐', 'queue'),
('ko-37', 'default', '아키텍처', 'architecture'),
('ko-38', 'default', '마이크로서비스', 'microservice'),
('ko-39', 'default', '설계', 'design'),
('ko-40', 'default', '패턴', 'pattern'),
('ko-41', 'default', '의존성', 'dependency'),
('ko-42', 'default', '확장성', 'scalability'),
('ko-43', 'default', '미들웨어', 'middleware'),
('ko-44', 'default', '엔드포인트', 'endpoint'),
('ko-45', 'default', '라우팅', 'routing'),
('ko-46', 'default', '게이트웨이', 'gateway'),
('ko-47', 'default', '프록시', 'proxy'),
('ko-48', 'default', '로드밸런서', 'load balancer'),
('ko-49', 'default', '서비스메시', 'service mesh'),
('ko-50', 'default', '모놀리식', 'monolithic'),
('ko-51', 'default', '백엔드', 'backend'),
('ko-52', 'default', '프론트엔드', 'frontend'),
('ko-53', 'default', '컨테이너', 'container'),
('ko-54', 'default', '파이프라인', 'pipeline'),
('ko-55', 'default', '모니터링', 'monitoring'),
('ko-56', 'default', '인프라', 'infrastructure'),
('ko-57', 'default', '클라우드', 'cloud'),
('ko-58', 'default', '헬스체크', 'health check'),
('ko-59', 'default', '네임스페이스', 'namespace'),
('ko-60', 'default', '노드', 'node'),
('ko-61', 'default', '서비스', 'service'),
('ko-62', 'default', '볼륨', 'volume'),
('ko-63', 'default', '시크릿', 'secret'),
('ko-64', 'default', '백업', 'backup'),
('ko-65', 'default', '복원', 'restore'),
('ko-66', 'default', '쿼리', 'query'),
('ko-67', 'default', '인덱스', 'index'),
('ko-68', 'default', '트랜잭션', 'transaction'),
('ko-69', 'default', '벡터', 'vector'),
('ko-70', 'default', '임베딩', 'embedding'),
('ko-71', 'default', '유사도', 'similarity'),
('ko-72', 'default', '연결풀', 'connection pool'),
('ko-73', 'default', '머신러닝', 'machine learning'),
('ko-74', 'default', '추론', 'inference'),
('ko-75', 'default', '파인튜닝', 'fine-tuning'),
('ko-76', 'default', '모델', 'model'),
('ko-77', 'default', '토큰', 'token'),
('ko-78', 'default', '검색증강생성', 'retrieval augmented generation'),
('ko-79', 'default', '청킹', 'chunking'),
('ko-80', 'default', '리랭킹', 'reranking');
