-- Traditional Chinese Glossary (繁體中文專業詞義強制對齊 Seed)
-- For homelab and common software development terms.
-- Workspace ID is 'default', users can import it to any workspace.

-- General Software & Architecture Terms
INSERT OR REPLACE INTO dictionary (id, workspace_id, key, value) VALUES 
('tc-1', 'default', '認證', 'authentication'),
('tc-2', 'default', '設定', 'configuration'),
('tc-3', 'default', '部署', 'deployment'),
('tc-4', 'default', '安裝', 'installation'),
('tc-5', 'default', '資料庫', 'database'),
('tc-6', 'default', '伺服器', 'server'),
('tc-7', 'default', '客戶端', 'client'),
('tc-8', 'default', '使用者', 'user'),
('tc-9', 'default', '管理員', 'admin'),
('tc-10', 'default', '安全性', 'security'),
('tc-11', 'default', '權限', 'permission'),
('tc-12', 'default', '登入', 'login'),
('tc-13', 'default', '密碼', 'password'),
('tc-14', 'default', '搜尋', 'search'),
('tc-15', 'default', '文檔', 'document'),
('tc-16', 'default', '檔案', 'file'),
('tc-17', 'default', '上傳', 'upload'),
('tc-18', 'default', '下載', 'download'),
('tc-19', 'default', '錯誤', 'error'),
('tc-20', 'default', '除錯', 'debugging'),
('tc-21', 'default', '修復', 'fix'),
('tc-22', 'default', '測試', 'test'),
('tc-23', 'default', '建置', 'build'),
('tc-24', 'default', '執行', 'run'),
('tc-25', 'default', '函式', 'function'),
('tc-26', 'default', '變數', 'variable'),
('tc-27', 'default', '型態', 'type'),
('tc-28', 'default', '模組', 'module'),
('tc-29', 'default', '套件', 'package'),
('tc-30', 'default', '程式庫', 'library'),
('tc-31', 'default', '框架', 'framework'),
('tc-32', 'default', '元件', 'component'),
('tc-33', 'default', '介面', 'interface'),
('tc-34', 'default', '環境變數', 'environment variable'),
('tc-35', 'default', '快取', 'cache'),
('tc-36', 'default', '佇列', 'queue'),
('tc-37', 'default', '架構', 'architecture'),
('tc-38', 'default', '微服務', 'microservice'),
('tc-39', 'default', '設計', 'design'),
('tc-40', 'default', '模式', 'pattern'),
('tc-41', 'default', '依賴', 'dependency'),
('tc-42', 'default', '擴充性', 'scalability'),
('tc-43', 'default', '中介軟體', 'middleware'),
('tc-44', 'default', '端點', 'endpoint'),
('tc-45', 'default', '路由', 'routing'),
('tc-46', 'default', '閘道', 'gateway'),
('tc-47', 'default', '代理', 'proxy'),
('tc-48', 'default', '負載平衡', 'load balancer'),
('tc-49', 'default', '服務網格', 'service mesh'),
('tc-50', 'default', '單體', 'monolithic'),
('tc-51', 'default', '後端', 'backend'),
('tc-52', 'default', '前端', 'frontend'),
('tc-53', 'default', '容器', 'container'),
('tc-54', 'default', '管線', 'pipeline'),
('tc-55', 'default', '監控', 'monitoring'),
('tc-56', 'default', '基礎設施', 'infrastructure'),
('tc-57', 'default', '雲端', 'cloud'),
('tc-58', 'default', '健康檢查', 'health check'),
('tc-59', 'default', '命名空間', 'namespace'),
('tc-60', 'default', '節點', 'node'),
('tc-61', 'default', '服務', 'service'),
('tc-62', 'default', '資料卷', 'volume'),
('tc-63', 'default', '機密', 'secret'),
('tc-64', 'default', '備份', 'backup'),
('tc-65', 'default', '還原', 'restore'),
('tc-66', 'default', '查詢', 'query'),
('tc-67', 'default', '索引', 'index'),
('tc-68', 'default', '交易', 'transaction'),
('tc-69', 'default', '向量', 'vector'),
('tc-70', 'default', '嵌入', 'embedding'),
('tc-71', 'default', '相似度', 'similarity'),
('tc-72', 'default', '連線池', 'connection pool'),
('tc-73', 'default', '機器學習', 'machine learning'),
('tc-74', 'default', '推論', 'inference'),
('tc-75', 'default', '微調', 'fine-tuning'),
('tc-76', 'default', '模型', 'model'),
('tc-77', 'default', '詞記', 'token'),
('tc-78', 'default', '檢索增強生成', 'retrieval augmented generation'),
('tc-79', 'default', '切片', 'chunking'),
('tc-80', 'default', '重排', 'reranking');
